package com.example.meydoon.Intro;

import android.os.Bundle;
import android.support.annotation.Nullable;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentTransaction;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;

import com.example.meydoon.R;

/**
 * Created by hooma on 2/5/2017.
 */
public class VerifyMobileFragment extends Fragment {

    private Button btn_verify;
    private EditText code;
    private TextView resend_verification_code;
    private TextView back_to_phone_enter;


    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.mobile_verification, container, false);
        return view;
    }

    @Override
    public void onViewCreated(View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);


        btn_verify = (Button)view.findViewById(R.id.btn_go_to_submit_page);


        btn_verify.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View view) {
                code = (EditText)view.findViewById(R.id.txt_set_verification_code);

                /* Check whether the entered code matches the one generated by Meydoon
                   If so, submit users phone to DB and create the user then go to the next page

                   If the code doesn't match, show a text that says so
                */



            }
        });

        resend_verification_code = (TextView)view.findViewById(R.id.link_resend_verification_code);
        resend_verification_code.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                // ====================> Resend a Verification Code <=====================
            }
        });


        // ********* Go back to Mobile Enter layout *********
        back_to_phone_enter = (TextView)view.findViewById(R.id.txt_back_to_phone_verification);
        back_to_phone_enter.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                SignUpMobileFragment newFragment = new SignUpMobileFragment();
                Bundle args = new Bundle();
                newFragment.setArguments(args);
                FragmentTransaction transaction = getFragmentManager().beginTransaction();

                // Replace whatever is in the fragment_container view with this fragment,
                // and add the transaction to the back stack so the user can navigate back
                transaction.replace(R.id.user_sign_up_container, newFragment);
                // Commit the transaction
                transaction.commit();


            }
        });

    }

}
